In [241]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import hvplot.pandas
from collections import Counter
%matplotlib inline

In [242]:
df = pd.read_csv('clean_data.csv')
df = df.drop(['Unnamed: 0','high_quality'],axis=1)
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  white  
0      8.8        6      1  
1      9.5        6      1  
2     10.1        6      1  
3      9.9        6      1  
4      9.9        6      1

In [243]:

X = df.drop('quality',axis=1)
y = df['quality']

In [244]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [245]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-0.1671586 , -0.4235636 ,  0.28424515, ..., -0.5459591 ,
        -1.41855821,  0.57136659],
       [-0.70742728, -0.24123152,  0.14652315, ..., -0.27706392,
        -0.83161516,  0.57136659],
       [ 0.68183504, -0.36278624,  0.55968916, ..., -0.6131829 ,
        -0.32852111,  0.57136659],
       ...,
       [-0.70742728,  1.03509307, -1.2995579 , ...,  1.47075478,
         0.42611996, -1.75018984],
       [-1.01615224,  1.85558744, -1.3684189 , ...,  1.2018596 ,
        -0.2446721 , -1.75018984],
       [-0.938971  , -0.18045416,  1.04171618, ...,  0.86574062,
         0.42611996, -1.75018984]])

In [246]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25, random_state=43)

In [247]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
predictions

array([5.80336462, 6.75375607, 5.80861637, ..., 5.92498789, 5.34711193,
       6.40172258])

In [248]:
Results = y_test.to_frame()
Results["Predicted Quality"] = predictions

Results[:10]

quality  Predicted Quality
4708        6           5.803365
968         7           6.753756
1948        7           5.808616
4805        6           5.388706
2126        5           5.172846
2497        5           5.712405
6121        6           6.477585
3405        6           5.786843
797         6           5.964111
5525        5           4.899725

In [249]:
# Relevant metrics - score, r2, mse, rmse, std
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

score = model.score(X_test,y_test)
r2 = r2_score(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
std = np.std(y)

In [250]:
# Print releveant metrics.
print(f"The score is {score}.")
print(f"The r2 is {r2}.")
print(f"The mean squared error is {mse}.")
print(f"The root mean squared error is {rmse}.")
print(f"The standard deviation is {std}.") 

The score is 0.28027117863462725.
The r2 is 0.28027117863462725.
The mean squared error is 0.5341424264033833.
The root mean squared error is 0.7308504815647201.
The standard deviation is 0.8731880644450458.


## Logistic Regression

In [251]:
df = pd.read_csv('clean_data.csv')
df.head()

Unnamed: 0  fixed acidity  volatile acidity  citric acid  residual sugar  \
0           0            7.0              0.27         0.36            20.7   
1           1            6.3              0.30         0.34             1.6   
2           2            8.1              0.28         0.40             6.9   
3           3            7.2              0.23         0.32             8.5   
4           4            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  white  high_quality  
0       0.45      8.8        6      1             0  
1       0.49      9.5        6      1             0  
2       0.44     10.1        6      1             0  
3       0.40      9.9        6      1             0  
4       0.40      9.9        6      1             0

In [252]:
df = df.drop(['quality'],axis=1)
X = df.drop('high_quality',axis=1)
y = df['high_quality']


In [253]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [254]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25, random_state=43)

In [255]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)


LogisticRegression(random_state=1)

In [256]:
from sklearn.metrics import balanced_accuracy_score
predictions = model.predict(X_test)
balanced_accuracy_score(y_test, predictions)

0.6319840433466626

In [257]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[1241,   66],
       [ 218,  100]])

In [258]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.85      0.95      0.90      1307
           1       0.60      0.31      0.41       318

    accuracy                           0.83      1625
   macro avg       0.73      0.63      0.66      1625
weighted avg       0.80      0.83      0.80      1625



In [259]:
y.value_counts()

0    5220
1    1277
Name: high_quality, dtype: int64

## Undersampling Data on Logistic Regression

In [260]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

# View the count of target classes with Counter
Counter(y_resampled)

Counter({0: 959, 1: 959})

In [261]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [262]:
# Calculate the balanced accuracy score
y_pred = model.predict(X_test)
#scores['CC'] = balanced_accuracy_score(y_test, y_pred)
balanced_accuracy_score(y_test, y_pred)

0.7344932703921314

In [263]:
# Display the confusion matrix
confusion_matrix(y_test,y_pred)

array([[913, 394],
       [ 73, 245]])

In [264]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.70      0.80      1307
           1       0.38      0.77      0.51       318

    accuracy                           0.71      1625
   macro avg       0.65      0.73      0.65      1625
weighted avg       0.82      0.71      0.74      1625

